'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import {cookies} from 'next/headers'
import {useState, useEffect} from 'react'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const [userName, setuserName] = useState<string>('')


useEffect(() => {
  let checkCookie = setInterval(() => {
     let cookieData: any = cookies().get('username')
     
     if (cookieData)
     {
       setuserName(cookieData)
       clearInterval(checkCookie)
     }

  }, 3000)

  return () => clearInterval(checkCookie)
}, [])

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {userName ? <Navbar username={userName}/> : <Navbar username={null} />}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
